import './globals.css';
import NavBar from './components/nav-bar/navbar';
import { Varela_Round } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const valera = Varela_Round({
  weight: '400',
  subsets: ['latin']
});

export default function RootLayout ({ children }) {
  return (
    <html lang='en' className={valera.className}>
      <head>
        <title>Yaz Montecinos Portfolio</title>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className='font-lato' style={{ margin: '0px' }}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
